### ISSUE TITLE
Fix cwise browserify transform

### ISSUE THREAD

**Issue by rreusser** [scijs/ndarray-householder-qr#3]
@mikolalysenko — I think a bunch of my modules will fail on browserify because I may have left the cwise transform in without a cwise dependency. Can you confirm:

**All modules that directly or indirectly include cwise as a dependency should have the browserify transform in package.json and a cwise dependency?**

I also need to check whether my dependencies + sub-dependencies are [pulling in duplicate dependencies when browserified](http://stackoverflow.com/questions/27931982/how-do-i-prevent-browserify-from-including-multiple-versions-of-sub-dependencies).

**Comment by mikolalysenko** [comment]
Yes, if you are using cwise you need to add it as a dependency.  Regarding duplicate dependencies, it is no big deal.  Just run npm dedupe before you bundle it:

https://docs.npmjs.com/cli/dedupe

It will get even better in npm 3, where dependency deduplication will become more streamlined.

**Comment by rreusser** [comment]
Perfect, thanks!

**Comment by rreusser** [comment]
Added proper dependency. Now works with browserify.
